language: node_js
node_js:
  - "7"
sudo: false
dist: trusty

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -G npm-run
  - npm install --dev

script:
  - npm test
  - npm run bundle

deploy:
  provider: npm
  email: "TO_BE_DEFINED@TO_BE_DEFINED.com"
  api_key: "ENCRYPTED_VARIABLE"
  on:
    tags: true
    skip_cleanup: true
