const docTests = {
        absoluteURLsForInternalLinks : require('./absolute-urls-for-internal-links.js').absoluteURLsForInternalLinks,
        alertPrintInCode : require('./alert-print-in-code.js').alertPrintInCode,
        apiSyntaxHeadlines : require('./api-syntax-headlines.js').apiSyntaxHeadlines,
        articleLength : require('./article-length.js').articleLength,
        codeInPre : require('./code-in-pre.js').codeInPre,
        dataMacroNote : require('./data-macro-note.js').dataMacroNote,
        differentLocalLinks : require('./different-locale-links.js').differentLocalLinks,
        emptyBrackets : require('./empty-brackets.js').emptyBrackets,
        emptyElements : require('./empty-elements.js').emptyElements,
        exampleColonHeading : require('./example-colon-heading.js').exampleColonHeading,
        fontElement : require('./font-elements.js').fontElement,
        htmlComments : require('./html-comments.js').htmlComments,
        httpLinks : require('./http-links.js').httpLinks,
        incorrectlyWrappedSidebarMacros : require('./incorrectly-wrapped-sidebar-macros.js').incorrectlyWrappedSidebarMacros,
        invalidMacros : require('./invalid-macros.js').invalidMacros,
        lineLengthInPre : require('./line-length-in-pre.js').lineLengthInPre,
        linkCount : require('./link-count.js').linkCount,
        macroSyntaxError : require('./macro-syntax-error.js').macroSyntaxError,
        nameAttribute : require('./name-attribute.js').nameAttribute,
        oldURLs : require('./old-urls.js').oldURLs,
        preWithoutClass : require('./pre-without-class.js').preWithoutClass,
        shellPrompts : require('./shell-prompts.js').shellPrompts,
        spanCount : require('./span-count.js').spanCount,
        styleAttribute : require('./style-attribute.js').styleAttribute,
        summaryHeading : require('./summary-heading.js').summaryHeading,
        unnecessaryMacroParams : require('./unnecessary-macro-params.js').unnecessaryMacroParams,
        URLInLinkTitle : require('./url-in-link-title.js').URLInLinkTitle,
        wrongHighlightedLine : require('./wrong-highlighted-line.js').wrongHighlightedLine,
        wrongSyntaxClass : require('./wrong-syntax-class.js').wrongSyntaxClass
};

module.exports = docTests;
